import numpy as np
import pytest

from pyPolyMesher import Domain, PolyMesher, mesh_assessment
from pyPolyMesher.dFunctions import dCircle, dRectangle
from pyPolyMesher.exampleDomains import (
    CookDomain,
    HornDomain,
    MbbDomain,
    MichellDomain,
    SuspensionDomain,
    WrenchDomain,
)


MESH_CASES = [
    (CookDomain, 12, 5),
    (SuspensionDomain, 16, 5),
    (MichellDomain, 12, 5),
    (WrenchDomain, 12, 5),
    (HornDomain, 12, 5),
    (MbbDomain, 12, 5),
]


def square_sdf(points):
    return dRectangle(points, 0, 1, 0, 1)


def circle_sdf(points):
    return dCircle(points, 0, 0, 1)


@pytest.mark.parametrize("domain, nelem, maxiter", MESH_CASES, ids=lambda case: case.name if hasattr(case, "name") else str(case))
def test_example_domain_meshing_smoke(domain, nelem, maxiter):
    node, element, supp, load, points = PolyMesher(domain, nelem, maxiter)

    assert isinstance(node, np.ndarray)
    assert node.ndim == 2 and node.shape[1] == 2
    assert node.shape[0] > 0

    assert isinstance(element, list)
    assert len(element) > 0
    assert any(len(e) >= 3 for e in element if e is not None)

    assert isinstance(points, np.ndarray)
    assert points.ndim == 2 and points.shape[1] == 2
    assert points.shape[0] == nelem

    if domain.BC is None:
        assert supp is None
        assert load is None
    else:
        assert supp is not None
        assert load is not None
        assert isinstance(supp, np.ndarray)
        assert isinstance(load, np.ndarray)
        assert supp.ndim == 2 and supp.shape[1] == 3
        assert load.ndim == 2 and load.shape[1] == 3


@pytest.mark.parametrize(
    "domain, nelem, maxiter",
    [
        (Domain("synthetic-square", [0, 1, 0, 1], square_sdf), 9, 4),
        (Domain("synthetic-circle", [-1, 1, -1, 1], circle_sdf), 12, 4),
    ],
    ids=["square", "circle"],
)
def test_polymesher_with_autogenerated_initial_points(domain, nelem, maxiter):
    node, element, supp, load, points = PolyMesher(domain, nelem, maxiter)

    assert node.ndim == 2 and node.shape[1] == 2
    assert len(element) > 0
    assert points.shape == (nelem, 2)
    assert supp is None and load is None


@pytest.mark.parametrize(
    "domain, initial_points",
    [
        (
            Domain("synthetic-square-with-seed", [0, 1, 0, 1], square_sdf),
            np.array(
                [
                    [0.20, 0.20],
                    [0.80, 0.20],
                    [0.20, 0.80],
                    [0.80, 0.80],
                    [0.50, 0.50],
                    [0.35, 0.65],
                    [0.65, 0.35],
                    [0.15, 0.55],
                ]
            ),
        ),
        (
            Domain("synthetic-circle-with-seed", [-1, 1, -1, 1], circle_sdf),
            np.array(
                [
                    [0.0, 0.0],
                    [0.5, 0.0],
                    [-0.5, 0.0],
                    [0.0, 0.5],
                    [0.0, -0.5],
                    [0.3, 0.3],
                    [-0.3, 0.3],
                    [0.3, -0.3],
                ]
            ),
        ),
    ],
    ids=["square_seeded", "circle_seeded"],
)
def test_polymesher_with_user_supplied_initial_points(domain, initial_points):
    node, element, supp, load, points = PolyMesher(domain, initial_points.shape[0], 4, initial_points)

    assert node.ndim == 2 and node.shape[1] == 2
    assert len(element) > 0
    assert points.shape == initial_points.shape
    assert np.all(np.isfinite(node))
    assert supp is None and load is None


@pytest.mark.parametrize(
    "fixed_points",
    [np.array([[0.25, 0.25], [0.75, 0.75]]), np.array([[0.0, 0.0]])],
    ids=["two_fixed_points", "single_fixed_point"],
)
def test_polymesher_accepts_fixed_points_and_preserves_mesh_behavior(fixed_points):
    domain = Domain(
        "synthetic-square-fixed",
        [0, 1, 0, 1],
        square_sdf,
        PFix=fixed_points,
    )

    node, element, supp, load, points = PolyMesher(domain, 9, 4)

    assert node.ndim == 2 and node.shape[1] == 2
    assert len(element) > 0
    assert points.shape == (9, 2)
    assert np.all(np.isfinite(points))
    assert supp is None and load is None


def test_mesh_assessment_reports_expected_keys_and_values(capsys):
    node = np.array(
        [
            [0.0, 0.0],
            [1.0, 0.0],
            [1.0, 1.0],
            [0.0, 1.0],
        ]
    )
    element = [np.array([0, 1, 2, 3])]

    assessment = mesh_assessment(node, element, domain_area=1.0, verbose=False)

    expected_keys = {
        "Max. Mesh AR",
        "Average Mesh AR",
        "Shortest Length",
        "Avg. Length",
        "Range of Areas",
        "Standard Deviation of Areas",
        "Total Area Error (%)",
    }
    assert expected_keys.issubset(assessment.keys())
    assert assessment["Max. Mesh AR"] == pytest.approx(1.0)
    assert assessment["Average Mesh AR"] == pytest.approx(1.0)
    assert assessment["Shortest Length"] == pytest.approx(1.0)
    assert assessment["Avg. Length"] == pytest.approx(1.0)
    assert assessment["Range of Areas"] == pytest.approx((1.0, 1.0))
    assert assessment["Standard Deviation of Areas"] == pytest.approx(0.0)
    assert assessment["Total Area Error (%)"] == pytest.approx(0.0)

    mesh_assessment(node, element, domain_area=1.0, verbose=True)
    out = capsys.readouterr().out
    assert "Max. Mesh AR:" in out
    assert "Total Area Error (%)" in out
